# Generated by Django 6.1.1 on 2026-09-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('payroll_number', models.CharField(max_length=50, unique=True)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
            ],
        ),
    ]
